### ISSUE TITLE
Shareable URI for conference not working correctly

### ISSUE THREAD

**Issue by amarjeetkapoor1** [GreatDevelopers/Conversations#27] opened 2016-11-30 15:03 UTC
When we share URI for conference the URI that we get is not correct and doesn't go to correct activity.

**Comment by jugrajsingh** [comment] 2016-12-01 05:47
You mean share action from conference details page.

**Comment by jugrajsingh** [comment] 2016-12-01 05:48
If that, works fine for me

**Comment by jugrajsingh** [comment] 2016-12-01 08:45
I get that the issue is with the underscores.
It did not working with underscore for URIs of groups

**Comment by jugrajsingh** [comment] 2017-01-24 03:19
Problem resolved.
Close the issue.

**Closed as completed** 2017-02-05 17:47 UTC
